### ISSUE TITLE
function names not snake case

### ISSUE THREAD

**Issue by tronta** [andrewbaxter/terrars#1]
I saw a couple of functions which don't follow the name schema, e.g.
* set_memorymb
* set_cputype
* dnsvalidationtarget
* set_internaltunnelorg
* set_internaltunnelregion

Is there a reason for not using snake case?

**Comment by andrewbaxter** [comment]
My guess is that the Terraform provider is doing something nonstandard with naming... which provider is that?

**Comment by tronta** [comment]
I just looked into your hello world example.

**Comment by andrewbaxter** [comment]
Ah right, yeah, they're all smashed together here: https://registry.terraform.io/providers/fly-apps/fly/latest/docs/resources/machine -- you can see some fields are snake case, some have no separation.  Terrars derives the names from the provider's names, so in this case that's what we get.
